version: '2'

volumes:
  mariadb-data:
    driver: local
  redmine-data:
    driver: local

services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - mariadb-data:/bitnami/mariadb/data

  application:
    image: bitnami/redmine:latest
    ports:
      - 80:3000
    volumes:
      - redmine-data:/bitnami/redmine
    depends_on:
      - mariadb
